### ISSUE TITLE
グラレコを描く

### ISSUE THREAD

**Issue by shioue22** [furuhashilab/Youth_JOSM-Validation#2]
作業日：7/1

**Comment by shioue22** [comment]
![image](https://github.com/furuhashilab/Youth_JOSM-Validation/assets/106800258/f47d33c0-a848-4778-a1ab-48171b25934e)

![image](https://github.com/furuhashilab/Youth_JOSM-Validation/assets/106800258/337d0399-ab59-464e-9c32-b1563d1a552e)

**Comment by mapconcierge** [comment]
再提出が残っていたので、これだけ Re-Openします。

**Comment by shioue22** [comment]
## NEW
![IMG_4142](https://github.com/user-attachments/assets/8b49b593-78b0-447c-b067-25e16b2872dd)
