### ISSUE TITLE
グラレコの内容をまとめる・構成する

### ISSUE THREAD

**Issue by shioue22** [furuhashilab/Youth_JOSM-Validation#4]
Osmoseについて、UN Validationの講座を参考にまとめる

**Comment by shioue22** [comment]
**参考にできそうなサイト**

[https://mappers.un.org/learning/mod/book/view.php?id=405&chapterid=935](https://mappers.un.org/learning/mod/book/view.php?id=405&chapterid=935)

**Comment by shioue22** [comment]
@mikuhashi 
Osmose全般（Osmoseとは、操作方法など）[参考にしてください](https://mappers.un.org/learning/mod/book/view.php?id=405&chapterid=935)

@shioue22 
その他上級テクニック、フォロー　[参考サイト](https://mappers.un.org/learning/mod/book/view.php?id=405&chapterid=505)

**期限：6/30**

**Comment by shioue22** [comment]
内容まとめ（案）

[OverpassとWhodiditについて(Google Slide)](https://docs.google.com/presentation/d/16wifjGShyZgdKIZfiC7sjbYI6OMIVisIlJRpeQtFZCE/edit?usp=sharing)

優先順位としては、こんな感じがいいかなと思います。
1. **Osmose**
2. Overpass（余裕があれば）
3. Whodidit（余裕があれば）

**Comment by mikuhayashi** [comment]
https://docs.google.com/document/d/1e2rZhrj_VRQF0VwsNh2tfddJIOwW479eY8yLW1gp2I4/edit?usp=sharing
